### ISSUE TITLE
[TODO] Backend

### ISSUE THREAD

**Issue by Pliavi** [Pliavi/Improved-NLW-4-Rocketpay#1]
- [ ] Refactoring/simplifying things
  - [x] Do not delegate account functions on main module, but in an AccountActions module
  - [ ]  ~~Create a middleware before execute an operation, to be able to verify account states before any action (as not withdraw a blocked account)~~
  - [x] Follow this folder archtecture:
  ```ts
  app
  ├─ account
  │  ├─ operations
  │  │    └─ update_balance.ex
  │  ├─ account.ex
  │  ├─ accounts.ex
  │  └─ operations.ex
  └─ user
      ├─ user.ex
      └─ users.ex
  ```
- [ ] Authentication with token
- [x] User control functions
  - [x] Update user info
  - [x] Close account
- [x] Account control functions
  - [x] Block account (can't withdraw or transfer to other account, but can receive money)
- [x] Money tracking
- [ ] Bank statement

**Extras**
- [ ] Blocked account that receives money, get the money blocked to a separated field, and is added to balance after unblocked
- [ ] Recurrent transaction (withdraw/transfer automatically each month)
- [ ] Diary income based in brazillian _CDI (Certificado de Depósito Interbancário)_  
       https://console.hgbrasil.com/documentation/finance#obter-somente-taxas-cdi-selic
